export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ORDER_INGREDIENT = "ORDER_INGREDIENT";

export const RESET_INGREDIENT = "RESET_INGREDIENT";

export const ORDER_LOADED = "OREDER_LOADED";
export const LOADING_ORDER_FAILED = "LOADING_ORDER_FAILED";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
